function Out = stressNormal(Panel, ...
                            x_tc, ...
                            y_tc, ...
                            axial_stff, ...
                            EIx, ...
                            EIy, ...
                            EIxy, ...
                            Vz, ...
                            Mx, ...
                            My)

nPanels = Panel.nPanels;                        
                        
if nPanels < 1                        
    Out.stress_zz      = [];
    return
end

stress_zz     = cell(nPanels, 1);  % array of normal stresses, calculated around the perimeter of the panel
for n = 1:nPanels
    x     = Panel.x{n};
    y     = Panel.y{n};
    E_eff = Panel.E_eff(n);
    
    stress_zz{n} = E_eff .* ( Vz./axial_stff ...
                           - (My.*EIx + Mx.*EIxy)./(EIx.*EIy - EIxy.^2) .* (x - x_tc) ...
                           + (Mx.*EIy + My.*EIxy)./(EIx.*EIy - EIxy.^2) .* (y - y_tc) );
end

%% Collect the output
Out.stress_zz = stress_zz;     

end % function stressNormal
